#!/usr/bin/env bash
# nginx web server listening on port 80
# returns a page that contains the string "Hello World!"

sudo apt update
sudo apt install -y nginx
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/nginx.conf
pkill nginx
echo "Hello World!" > /var/www/html/index.html

